<?php

use Illuminate\Database\Seeder;

class BhPopularExchangesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('bh_popular_exchanges')->delete();

        \DB::table('bh_popular_exchanges')->insert([
            0 => [
                'id'         => 1,
                'exch_id'    => 55,
                'exchange'   => 'HitBTC',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://hitbtc.com/?ref_id=5a4d829c58916',
                'about'      => 'HitBTC - global trading platform with multi-currency support, operating since 2013. The exchange has markets for trading digital assets, tokens and ICOs and provides a wide range of tools as well as stable uptime.

The Platform development started with a 6 million euro venture investment agreement, as of the collaboration between software developers, finance professionals and experienced traders. The core matching engine is among the most advanced technological products in its class and implements innovative features such as real-time clearing, advanced order matching algorithms and has been acclaimed for its fault-tolerance, uptime and high availability',
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            1 => [
                'id'         => 2,
                'exch_id'    => 6,
                'exchange'   => 'Binance',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://www.binance.com/?ref=12325729',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            2 => [
                'id'         => 3,
                'exch_id'    => 105,
                'exchange'   => 'Coinbase/GDAX',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 0,
                'link'       => 'https://www.coinbase.com/join/51950ca286c21b84dd000021',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            3 => [
                'id'         => 4,
                'exch_id'    => 98,
                'exchange'   => 'CexIO',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 0,
                'link'       => 'https://cex.io/r/0/joeldg/0/',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            4 => [
                'id'         => 5,
                'exch_id'    => 77,
                'exchange'   => 'Poloniex',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://poloniex.com',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            5 => [
                'id'         => 6,
                'exch_id'    => 63,
                'exchange'   => 'Kraken',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://www.kraken.com',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            6 => [
                'id'         => 7,
                'exch_id'    => 52,
                'exchange'   => 'GDAX',
                'public_api' => 0,
                'coinigy'    => 0,
                'ccxt'       => 1,
                'link'       => 'https://www.coinbase.com/join/51950ca286c21b84dd000021',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            7 => [
                'id'         => 8,
                'exch_id'    => 96,
                'exchange'   => 'C-Cex',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 0,
                'link'       => 'https://c-cex.com/?rf=2BE2ED2FD83B6FAE',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            8 => [
                'id'         => 9,
                'exch_id'    => 32,
                'exchange'   => 'C-Cex',
                'public_api' => 0,
                'coinigy'    => 0,
                'ccxt'       => 1,
                'link'       => 'https://c-cex.com/?rf=2BE2ED2FD83B6FAE',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            9 => [
                'id'         => 10,
                'exch_id'    => 33,
                'exchange'   => 'CexIO',
                'public_api' => 0,
                'coinigy'    => 0,
                'ccxt'       => 1,
                'link'       => 'https://cex.io/r/0/joeldg/0/',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            10 => [
                'id'         => 11,
                'exch_id'    => 22,
                'exchange'   => 'BleuTrade',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://bleutrade.com/sign_up/148055',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            11 => [
                'id'         => 12,
                'exch_id'    => 43,
                'exchange'   => 'Cryptopia',
                'public_api' => 1,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://www.cryptopia.co.nz/Register?referrer=joeldg',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            12 => [
                'id'         => 13,
                'exch_id'    => 91,
                'exchange'   => 'YoBit',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://yobit.io/?bonus=Vwnof',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            13 => [
                'id'         => 14,
                'exch_id'    => 50,
                'exchange'   => 'Gatecoin',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://gatecoin.com/register?referralCode=WKBPME',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            14 => [
                'id'         => 15,
                'exch_id'    => 45,
                'exchange'   => 'Exmo',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://exmo.com/?ref=778749',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            15 => [
                'id'         => 16,
                'exch_id'    => 68,
                'exchange'   => 'Livecoin',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://livecoin.net/?from=Livecoin-KdJ73s2V',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            16 => [
                'id'         => 17,
                'exch_id'    => 89,
                'exchange'   => 'Wex',
                'public_api' => 1,
                'coinigy'    => 0,
                'ccxt'       => 1,
                'link'       => 'https://wex.nz',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
            17 => [
                'id'         => 18,
                'exch_id'    => 66,
                'exchange'   => 'LakeBTC',
                'public_api' => 0,
                'coinigy'    => 1,
                'ccxt'       => 1,
                'link'       => 'https://www.lakebtc.com/?ref=qsvodu',
                'about'      => null,
                'updated_at' => null,
                'created_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
